### ISSUE TITLE
[net] TCPClient can't run on linux

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1066]
### Description

TCPClient can't run on linux 

### Test Code

[TCPClient6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPClient6.js);
 
### Steps to Reproduction

1. `make BOARD=linux`
2. ./outdir/linux/release/jslinux samples/TCPClient6.js

### Actual Result

![selection_044](https://cloud.githubusercontent.com/assets/19813546/25371884/89f11b1e-29c5-11e7-9530-ac0e50959c78.png)

 ### Expected Result

TCP client could run on Linux according to the explanation at the front of [TCPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ6.js)

 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 4dda019 | Linux | Apr 25, 2017 | Fail

**Comment by jprestwo** [comment]
@qiaojingx, the "net" module is not supported on Linux, neither is "dgram".

**Comment by qiaojingx** [comment]
Closed since net and dgram modules are not supported on Linux.

**Comment by qiaojingx** [comment]
Reopen since still have some confusion.

@jprestwo, 
1. How can I run [TCPClient.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPClient6.js) if net module is not supported on linux? Does that means server and client will both run on Board(A101, k64f)?
2. What is the purpose of [TCPClient.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPClient6.js), is that for client testing, or just for cooperating with server testing?
3. As you mentioned in [TCPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ6.js). 
![capture](https://cloud.githubusercontent.com/assets/19813546/25416891/ec575ba8-2a72-11e7-9475-cfd34b78a4b6.PNG)
Does't that mean TCP Client could be set up on Linux? or I am misunderstanding that.

**Comment by cuiyanx** [comment]
@jprestwo 
Can I connect socket server with socket client coding by the other programming language(like java or python)?

**Comment by jprestwo** [comment]
@cuiyanx,

Sorry for the confusion, I should have mimicked the comments like @pfalcon did with his dgram samples.

1. TCPClient.js is still meant to be run on an Arduino 101 using 6lowpan. I am not sure if you could run it using two arduinos (TCPClient/TCPEchoServ6) but I doubt it because there would be no connection mechanism for BLE.

2. Goes with 1, all the TCP samples are meant for the Arduino/Zephyr board, not linux.

3. That comment means that you have to setup a TCP client on Linux, not related to ZJS at all. You can use `nc` for that:
`echo "hello" | nc -6 <ip> <port>`
This should be mentioned in the sample like it is for dgram.

I do have a python TCP client and server that I used for testing, the reason I didn't push those up is there was really no place for them in our repo. We are addressing this with #1046 and should have a place for it, somewhere like `tests/manual/net/`. For now though if its not too much trouble just finding a TCP client/server for python is the best route. I just found one online and modified it slightly to my usage so I can't push it up due to licensing.

**Comment by jprestwo** [comment]
This should help: https://github.com/01org/zephyr.js/pull/1071

**Comment by qiaojingx** [comment]
Closed since TCP Client also need to run on Arduino/Zephyr board.
