### ISSUE TITLE
Add basic support for nRF52 board

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#1268]

**Comment by jimmy-huang** [comment]
@poussa @grgustaf I can verify that I am able to build and run HelloWorld.js and most of the samples like Buffer.js that don't have any hardware dependenies, but BLE doesn't work.  The board I have is nRF52 DK, which is actually labeled nrf52_pca10040, instead of nrf52840_pca10056 we have in our README.  So I think we just need to update the instructions to reflect that, or we actually have different nRF52 boards?

**Comment by haoxli** [comment]
Verified the supported modules  on nRF52840 with `nrf52840_pca10056` and `nrf52_pca10040`.
commit id: f08230a 
- HelloWorld
- Buffer
- Console
- Event
- Performance
- Timers
