### ISSUE TITLE
how about support asynchronous and event-based program in zephyr.js?

### ISSUE THREAD

**Issue by BlankRain** [01org/zephyr.js#448]
In Arduino101, the Intel® Curie module contains two tiny cores, an x86 (Quark) and a 32-bit ARC .
So, could is support multithread feature?
Could we require [Rx.js ](https://github.com/Reactive-Extensions/RxJS)  to do someting in a Reactive way?

**Comment by jprestwo** [comment]
We are currently using the ARC core to support ADC and I2C (since the x86 core does not support those features). Since the Arduino 101 is already very small RAM/ROM wise, we allocate nearly all the RAM/ROM to the x86 side in order for it to run the JerryScript engine. There is no much room left on the ARC side to do much more than we are doing.

Also, since the Arduino 101 has this "different" architecture, supporting this multithreading feature would be platform specific, so all the work going into it would not be portable to other boards.

**Comment by baleboy** [comment]
Closing
