### ISSUE TITLE
[ashell] Not supported special character by "mv" command

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#736]
When using ashell command "mv" as rename file, the name of this file will not be supported by special character, like this "-".

Faild:
`mv temp.dat test-timer.js`

Success:
`mv temp.dat testTimer.js`

**Comment by grgustaf** [comment]
We should investigate what the allowed characters really are and support all of them. It's a FAT filesystem so I believe we've already realized filenames need to be in 8.3 format (e.g. thislong.txt). It's possible that @cuiyanx really ran into a problem because the filename was too long, not because of the hyphen character.

**Comment by cuiyanx** [comment]
As you say, I test that again, you are right.
Currently version: 
Faild: `mv temp.dat testTimer.js`
Success: `mv temp.dat test-la.js`
So, thanks to know and closed.
