### ISSUE TITLE
[REG][buffer] The value of readUInt8() is 255 not 0 when writeUInt8(-1)

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#853]
### Description

The value of readUInt8() is 255 not 0 when writeUInt8(-1)

### Test Code

[test-buffer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer.js); 
 
### Steps to Reproduction

1. `make JS=tests/test-buffer.js`
2. `make dfu`
 
### Actual Result

1. On Arduino 101, FRDM-K64F and Linux:
![selection_001](https://cloud.githubusercontent.com/assets/19813546/24139718/35a30b9a-0e58-11e7-99de-2ef1cc8dfba1.png)

### Expected Result

No error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | eaf24e9 | Arduino 101 | Mar 14, 2017 | Pass
master | eaf24e9 | FRDM-K64F | Mar 14, 2017 | Pass
master | eaf24e9 | Linux | Mar 14, 2017 | Fail
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Fail
master | 02d9471 | FRDM-K64F | Mar 21, 2017 | Fail
master | 02d9471 | Linux | Mar 21, 2017 | Fail
### Additional Information

The uncaught expection error issue is tracking here #852

**Comment by qiaojingx** [comment]
Closed by mistake

**Comment by haoxli** [comment]
@qiaojingx Geoff talked with me, this one is invalid check point because the document in https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_buf_writeuint8_value_offset_noassert says: "Behavior is undefined when **value** is anything other than an unsigned 8-bit integer." 
So there is no expected value, we should remove this case. Please close it.

**Comment by qiaojingx** [comment]
Closed this is invalid check point.
