### ISSUE TITLE
[uart] invalid arguments error thrown in test-uart.js

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#854]
### Description

 invalid arguments error thrown in test-uart.js

### Test Code

[test-uart.js](https://github.com/01org/zephyr.js/blob/master/tests/test-uart.js); 
 
### Steps to Reproduction

1. `make JS=tests/test-uart.js`
2. `make dfu`
 
### Actual Result

`[ERROR] Uncaught exception: TypeError: invalid arguments` error thrown and test-uart.js hangs at the last test case.
![test-uart](https://cloud.githubusercontent.com/assets/19813546/24141176/a28ea980-0e5d-11e7-9bd9-de5356aef801.png)

### Expected Result

No error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | eaf24e9 | Arduino 101 | Mar 14, 2017 | Pass
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Fail

**Comment by baleboy** [comment]
To be fixed before releasing 0.3 (and possibly before branching)

**Comment by jprestwo** [comment]
@qiaojingx, @baleboy,

First off, this was introduced after the ZVAL patch, so now an error is thrown if the arguments are bad, rather than the promise rejecting. This is why this issue exists. Now the question comes down to, if there is a programmatic error (bad arguments) should an error be thrown immediately, or should it be handled by the promise catch function?

@grgustaf and I discussed this and came to the conclusion that it should NOT be handled by the promise catch function and instead be thrown as an error (catchable by try/catch if required). There are good reasons on either side of the coin, but I think for our use cases we should not allow programmatic errors in our code, and instead immediately throw/exit/break the current application, which show the developer they did something wrong rather than letting it slip by. One reason would be if they never used .catch() it would just continue as if nothing went wrong.

If you agree with this, I think that last test case should be removed OR surrounded with a try/catch block. Thoughts?

**Comment by grgustaf** [comment]
Working as designed currently.

**Comment by cuiyanx** [comment]
Will be fix by #943

**Comment by qiaojingx** [comment]
Verified with updated case. No issue occurred. Closed
